Repository jenkinsci/workflow-cps-global-lib-plugin, pull requests merged in 2021-11, with the labels that each got.

#115 [JENKINS-66629] `SCMSourceRetriever` leaks `@libs` workspaces
  src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
  src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java
Labels: internal

#117 Drop dependency on Commons Codec
  src/test/java/org/jenkinsci/plugins/workflow/libs/ResourceStepTest.java
Labels: internal

#113 [JENKINS-66045] Fix NPE in cache exclusions
  src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration.java
  src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfigurationTest.java
Labels: bug

#119 Update parent pom and core requirement
  pom.xml
Labels: enhancement

#118 hacktoberfest - update master to controller
  src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/config.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/help-cachingConfiguration.html
Labels: documentation

#121 No need to override `reuseForks`
  pom.xml
Labels: test

#122 [JENKINS-60406] Replace RUN_SCRIPTS with ADMINISTER
  .gitignore
  src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepository.java
  src/main/java/org/jenkinsci/plugins/workflow/libs/GlobalLibraries.java
  src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
  src/main/resources/org/jenkinsci/plugins/workflow/libs/GlobalLibraries/config.jelly
  src/test/java/org/jenkinsci/plugins/workflow/libs/GlobalLibrariesTest.java
Labels: enhancement

#123 Add Dependabot configuration
  .github/dependabot.yml
Labels: dependencies
