Repository jenkinsci/workflow-cps-global-lib-plugin, pull requests merged in 2021-06, with the labels that each got.

#109 Enable release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CHANGELOG.md
  README.md
Labels: documentation

#111 Update plugin POM and BOM
  .mvn/extensions.xml
  pom.xml
Labels: internal

#101 [JENKINS-38609] Shared Library non ROOT support
  src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
  src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
  src/main/resources/org/jenkinsci/plugins/workflow/libs/Messages.properties
  src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMRetriever/config.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMRetriever/config.properties
  src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMRetriever/help-libraryPath.html
  src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever/config.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever/config.properties
  src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever/help-libraryPath.html
  src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java
Labels: enhancement
